import Layout from "~/shared/Layout";
import Window from "~/shared/ui/Window";

const Explorer = () => {
  return (
    <Layout title="Explorer">
      <Window
        styled="w-full h-full"
        title="Explorer"
        closeButton
        bodyStyled="border-[1px] border-[#86847b] h-full bg-white overflow-y-auto"
        fullScreen
      >
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
        <p>s</p>
      </Window>
    </Layout>
  );
};

export default Explorer;
