import { ReactNode } from "react";
import Head from "next/head";
import { useMediaQuery } from "react-responsive";

import BottomBar from "./ui/BottomBar";

const bottomHeight = 35;

interface Props {
  children?: ReactNode;
  title?: string;
}

const Layout = ({ title = "undefined", children }: Props) => {
  const isMobile = useMediaQuery({ query: "(pointer:coarse)" });

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/Windows XP.ico" />
      </Head>
      <main
        className="
          mx-auto flex h-screen max-w-[1080px] flex-col items-start px-[16px] pt-[16px]
          [@media(pointer:coarse)]:max-w-[500px] [@media(pointer:coarse)]:items-center
          [@media(pointer:coarse)]:px-[16px] [@media(pointer:coarse)]:pt-[8px]
        "
        style={
          !isMobile
            ? { paddingBottom: bottomHeight + 16 }
            : { paddingBottom: bottomHeight + 8 }
        }
      >
        {children}
      </main>
      <BottomBar bottomHeight={bottomHeight} />
    </>
  );
};

export default Layout;
